name: EasyXJDF Release

on:
  push:
    tags:
      - EasyXJDF-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Debug
        run: echo ${GITHUB_REF##*XJDF-}

      - name: Set Version
        run: mvn versions:set -DnewVersion=${GITHUB_REF##*XJDF-}

      - name: Build Project
        run: mvn install

      - name: Create release
        uses: Roang-zero1/github-create-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: Roang-zero1/github-upload-release-artifacts-action@master
        with:
          args:
            - target
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}