name: EasyXJDF Release

on:
  push:
    tags:
      - EasyXJDF-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Debug
        run: echo ${GITHUB_REF##*XJDF-}

      - name: Set Version
        run: mvn versions:set -DnewVersion=${GITHUB_REF##*XJDF-}

      - name: Build Project
        run: mvn install

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'target/*.exe'