name: SNAPSHOT Build for EasyXJDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn install

      - name: Debug
        run: ls -l target

      - uses: actions/upload-artifact@v1
        with:
          name: exe
          path: target/CIP4 EasyXJDF dev-SNAPSHOT.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn install

      - name: Debug
        run: ls -l target

      - uses: actions/upload-artifact@v1
        with:
          name: dmg
          path: target/CIP4 EasyXJDF dev-SNAPSHOT.dmg
